# -*- coding: utf-8 -*-
"""app_explore_chinook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QoNRbfw6038nfVIZbP-D8QIG7Aw65pRm
"""

import sqlite3
import pandas as pd
import streamlit as st          # add this

st.title("Music Store")         # add this

conn = sqlite3.connect('Chinook_Sqlite.sqlite')
df = pd.read_sql("""
    SELECT g.Name as Genre, COUNT(t.TrackId) as Tracks
    FROM Track t
    JOIN Genre g ON t.GenreId = g.GenreId
    GROUP BY g.Name
    ORDER BY Tracks DESC
    LIMIT 5
""", conn)
conn.close()

st.dataframe(df)                # replace print(df) with this